<?php

/**
 * A fingerprint of what is in the database.
 *
 *   php dev/stress-verify.php > before.txt      # on SQLite
 *   php dev/stress-verify.php > after.txt       # on PostgreSQL
 *   diff before.txt after.txt
 *
 * Row counts alone would pass a migration that turned every apostrophe into a
 * question mark, dropped every NULL to an empty string, or rounded every price.
 * So this also hashes the content, column by column, in a defined order.
 *
 * What it deliberately excludes: ids and timestamps generated by the database,
 * because a correct migration is free to renumber. What it deliberately
 * includes: NULL-versus-empty, because that distinction is where migrations
 * quietly lose meaning, and it is invisible in any row count.
 */

require_once __DIR__ . '/../includes/database/connection.php';

$db = wallos_database_connect();
$driver = $db->driver();

/**
 * Every table, whichever backend is underneath.
 *
 * @param WallosDatabase $db
 * @return string[]
 */
function fingerprint_tables($db)
{
    $tables = [];

    if ($db->driver() === 'pgsql') {
        $result = $db->query("SELECT table_name AS name FROM information_schema.tables
                              WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'
                              ORDER BY table_name");
    } else {
        $result = $db->query("SELECT name FROM sqlite_master WHERE type = 'table'
                              AND name NOT LIKE 'sqlite_%' ORDER BY name");
    }

    while ($result !== false && $row = $result->fetchArray(SQLITE3_ASSOC)) {
        $tables[] = $row['name'];
    }

    return $tables;
}

/**
 * @param WallosDatabase $db
 * @param string         $table
 * @return string[]
 */
function fingerprint_columns($db, $table)
{
    $columns = [];

    if ($db->driver() === 'pgsql') {
        $statement = $db->prepare('SELECT column_name AS name FROM information_schema.columns
                                   WHERE table_schema = current_schema() AND table_name = :table
                                   ORDER BY column_name');
        $statement->bindValue(':table', $table);
        $result = $statement->execute();
    } else {
        // pragma_table_info takes its argument inline.
        $result = $db->query("SELECT name FROM pragma_table_info('" . str_replace("'", "''", $table) . "')");
    }

    while ($result !== false && $row = $result->fetchArray(SQLITE3_ASSOC)) {
        $columns[] = $row['name'];
    }

    sort($columns);

    return $columns;
}

/**
 * A stable rendering of one value.
 *
 * NULL and '' are rendered differently on purpose: SQLite is relaxed about the
 * distinction and PostgreSQL is not, so a migration that flattens one into the
 * other has to show up here rather than in a puzzled bug report later.
 *
 * Numbers are normalised because 19.99 may arrive as '19.99' or 19.99 depending
 * on the driver, and that difference is not a data difference.
 *
 * @param mixed $value
 * @return string
 */
function fingerprint_value($value)
{
    if ($value === null) {
        return '<null>';
    }
    if (is_bool($value)) {
        return $value ? '<true>' : '<false>';
    }
    if (is_numeric($value) && $value !== '') {
        $float = (float) $value;
        // Integers keep their exact form; fractions are rounded to the precision
        // money is actually stored at.
        return $float == (int) $float ? (string) (int) $float : rtrim(rtrim(number_format($float, 6, '.', ''), '0'), '.');
    }

    return (string) $value;
}

$tables = fingerprint_tables($db);

printf("# wallos fingerprint (%s, %d tables)\n", $driver, count($tables));

foreach ($tables as $table) {
    // Generated by the database and legitimately different after a migration.
    if (in_array($table, ['migrations', 'oidc_discovery_cache'], true)) {
        continue;
    }

    $columns = fingerprint_columns($db, $table);
    // ids may be renumbered by a correct migration; timestamps are set on insert.
    $content = array_values(array_filter($columns, fn($c) => !in_array($c, ['id', 'created_at', 'migrated_at', 'timestamp'], true)));

    $count = (int) $db->scalar('SELECT COUNT(*) FROM ' . $table);

    if ($content === [] || $count === 0) {
        printf("%-30s rows=%-7d columns=%s\n", $table, $count, implode(',', $columns));
        continue;
    }

    // Ordered by every content column so the hash does not depend on storage
    // order, which two databases have no reason to agree on.
    $quoted = array_map(fn($c) => '"' . $c . '"', $content);
    $result = $db->query('SELECT ' . implode(', ', $quoted) . ' FROM ' . $table
        . ' ORDER BY ' . implode(', ', $quoted));

    $hash = hash_init('sha256');
    $rows = 0;
    while ($result !== false && $row = $result->fetchArray(SQLITE3_ASSOC)) {
        $rendered = [];
        foreach ($content as $column) {
            $rendered[] = $column . '=' . fingerprint_value($row[$column] ?? null);
        }
        hash_update($hash, implode('|', $rendered) . "\n");
        $rows++;
    }

    printf("%-30s rows=%-7d sha256=%s columns=%s\n",
        $table, $rows, substr(hash_final($hash), 0, 16), implode(',', $columns));
}

$db->close();
